### ISSUE TITLE
can't play mp3 format for sound

### ISSUE THREAD

**Issue by ugurbolat** [marcinkoziej/org-pomodoro#92]
I wanted to customize org-pomodoro-start-sound etc. but can't play mp3 :/

Does it have to do with this package using sound-wav to play sound and can't play mp3?

**Comment by japhir** [comment]
I had this issue as well when trying to [play a sound once I mark a task as done](https://github.com/japhir/ArchConfigs/blob/master/myinit.org#play-bell-sound-when-task-is-marked-as-done), ended up just converting the file using ffmpeg!

**Comment by ugurbolat** [comment]
a nice workaround and will convert them too
